/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnderecoObraDTO } from './enderecoObraDTO';

export interface CreateObraDTO {
    contratante?: string;
    contratada?: string;
    projeto?: string;
    numeroContrato?: string;
    dataInicio?: string;
    dataPrevistaFim?: string;
    observacao?: string;
    fiscalId?: number;
    engenheiroIds?: Set<number>;
    endereco?: EnderecoObraDTO;
}

