/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EditUserDTO { 
    id?: number;
    login?: string;
    name?: string;
    password?: string;
    role?: EditUserDTO.RoleEnum;
    phone1?: string;
    phone2?: string;
    crea?: string;
    creaUf?: string;
    cpf?: string;
    enabled?: boolean;
    address?: string;
    addressNumber?: string;
    zipCode?: string;
    complement?: string;
    city?: string;
    state?: string;
}
export namespace EditUserDTO {
    export const RoleEnum = {
        Admin: 'ADMIN',
        Gestor: 'GESTOR',
        Engenheiro: 'ENGENHEIRO',
        Fiscal: 'FISCAL',
        User: 'USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


