/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileDTO } from './userProfileDTO';
import { EnderecoObraDTO } from './enderecoObraDTO';


export interface ObraResponseDTO {
    id?: number;
    contratante?: string;
    contratada?: string;
    projeto?: string;
    status?: ObraResponseDTO.StatusEnum;
    dataInicio?: string;
    dataPrevistaFim?: string;
    observacao?: string;
    fiscal?: UserProfileDTO;
    engenheiros?: Set<UserProfileDTO>;
    endereco?: EnderecoObraDTO;
}
export namespace ObraResponseDTO {
    export const StatusEnum = {
        Ativa: 'ATIVA',
        Inativa: 'INATIVA'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


