/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateObraDTO { 
    contratante?: string;
    contratada?: string;
    projeto?: string;
    fiscalId?: number;
    engenheiroIds?: Set<number>;
}

