/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthenticationDTO } from '../model/models';
import { LoginResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /auth/login
     * @param authenticationDTO 
     */
    login(authenticationDTO: AuthenticationDTO, extraHttpRequestParams?: any): Observable<LoginResponseDTO>;

}
