/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UploadFileRequest } from '../model/models';
import { UploadFileResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FileUploadTestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/files/test/download/{fileName}
     * @param fileName 
     */
    downloadFile(fileName: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @endpoint post /api/files/test/upload
     * @param uploadFileRequest 
     */
    uploadFile(uploadFileRequest?: UploadFileRequest, extraHttpRequestParams?: any): Observable<UploadFileResponseDTO>;

}
