/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateObraDTO } from '../model/models';
import { ObraResponseDTO } from '../model/models';
import { PageObraResponseDTO } from '../model/models';
import { UpdateObraDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ObraControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /obra
     * @param createObraDTO 
     */
    create(createObraDTO: CreateObraDTO, extraHttpRequestParams?: any): Observable<ObraResponseDTO>;

    /**
     * 
     * 
     * @endpoint delete /obra/{id}
     * @param id 
     */
    deactivate(id: number, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint get /obra/{id}
     * @param id 
     */
    findById(id: number, extraHttpRequestParams?: any): Observable<ObraResponseDTO>;

    /**
     * 
     * 
     * @endpoint get /obra
     * @param page 
     * @param size 
     * @param sortField 
     * @param sortDir 
     * @param term 
     * @param status 
     */
    search(page?: number, size?: number, sortField?: string, sortDir?: string, term?: string, status?: 'ATIVA' | 'INATIVA', extraHttpRequestParams?: any): Observable<PageObraResponseDTO>;

    /**
     * 
     * 
     * @endpoint put /obra/{id}
     * @param id 
     * @param updateObraDTO 
     */
    update(id: number, updateObraDTO: UpdateObraDTO, extraHttpRequestParams?: any): Observable<ObraResponseDTO>;

}
