/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EditUserDTO } from '../model/models';
import { PageUserProfileDTO } from '../model/models';
import { RegisterDTO } from '../model/models';
import { UserProfileDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /user/delete/{id}
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint put /user/edit
     * @param editUserDTO 
     */
    edit(editUserDTO: EditUserDTO, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint get /user/me
     */
    getMe(extraHttpRequestParams?: any): Observable<UserProfileDTO>;

    /**
     * 
     * 
     * @endpoint get /user/{id}
     * @param id 
     */
    getUserProfile(id: number, extraHttpRequestParams?: any): Observable<UserProfileDTO>;

    /**
     * 
     * 
     * @endpoint get /user/all
     */
    listAll(extraHttpRequestParams?: any): Observable<Array<UserProfileDTO>>;

    /**
     * 
     * 
     * @endpoint post /user/register
     * @param registerDTO 
     */
    register(registerDTO: RegisterDTO, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @endpoint get /user/search
     * @param page 
     * @param size 
     * @param sortField 
     * @param sortDir 
     * @param term 
     * @param role 
     * @param hideInactive 
     */
    search1(page?: number, size?: number, sortField?: string, sortDir?: string, term?: string, role?: 'ADMIN' | 'GESTOR' | 'ENGENHEIRO' | 'FISCAL' | 'USER', hideInactive?: boolean, extraHttpRequestParams?: any): Observable<PageUserProfileDTO>;

}
